#!/bin/bash

set -euo pipefail

main() {
  local script_dir
  script_dir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
  local root_dir
  root_dir="$(dirname "$script_dir")"

  local extra_env
  extra_env="$(env -i $(cat "$BUILDKITE_ENV_FILE" | grep -v "BUILDKITE_" | xargs) $(which jq) -n -c env)"

  local pod
  pod="$(jq -n -f "$root_dir/lib/pod.jq" --argjson extra_env $extra_env)"

  local pod_name
  pod_name="$(echo -n $pod | jq -r .metadata.name)"

  echo "--- :kubernetes: Starting pod"
  echo -n "$pod" | kubectl create -f -
  kubectl wait --for=condition=Ready --timeout="$(jq -r -n 'env.BUILDKITE_TIMEOUT | tonumber * 60')s" pod "$pod_name" || (exit 124)
  kubectl cp -c run "$(which buildkite-agent)" "$pod_name:/usr/local/bin/" || true

  echo "+++ :kubernetes: Running command: $BUILDKITE_COMMAND"
  kubectl exec -c run "$pod_name" -- $BUILDKITE_COMMAND
}

main "$@"
